server.port = 8080


spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/myDB
spring.datasource.username=root
spring.datasource.password=1234



spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=land5113@naver.com
spring.mail.password=sky8746@
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com


mybatis.mapper-locations=classpath:mapper/*.xml




mybatis.type-aliases-package=Seoul.tour.dto


mybatis.configuration.map-underscore-to-camel-case=true


#spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
#
#
#spring.jpa.hibernate.ddl-auto=create
#
